version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myapp.settings.production
    volumes:
      - ./myapp:/myapp  
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myapppassword
